"""
Data models for the Autonomous Code Improvement System.

Defines Pydantic models for suggestions, verdicts, and run state.
"""

from datetime import datetime
from enum import Enum
from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field
import uuid


class SuggestionStatus(str, Enum):
    """Status of a code improvement suggestion."""
    PENDING = "pending"           # Awaiting user review
    ACCEPTED = "accepted"         # User accepted, ready for implementation
    REJECTED = "rejected"         # User rejected
    IN_PROGRESS = "in_progress"   # Worker is implementing
    COMPLETED = "completed"       # Successfully implemented and verified
    FAILED = "failed"             # Implementation or verification failed


class SuggestionCategory(str, Enum):
    """Category of improvement."""
    SECURITY = "security"
    PERFORMANCE = "performance"
    MAINTAINABILITY = "maintainability"
    DOCUMENTATION = "documentation"
    TESTING = "testing"
    REFACTORING = "refactoring"
    BUG_FIX = "bug_fix"
    FEATURE = "feature"


class Suggestion(BaseModel):
    """A code improvement suggestion generated by the Planner."""
    id: str = Field(default_factory=lambda: str(uuid.uuid4())[:8])
    title: str = Field(..., description="Short title for the suggestion")
    description: str = Field(..., description="Detailed description of what to improve")
    category: SuggestionCategory = Field(default=SuggestionCategory.REFACTORING)
    priority: int = Field(default=5, ge=1, le=10, description="Priority 1-10, higher is more important")
    affected_files: List[str] = Field(default_factory=list, description="Files that will be modified")
    acceptance_criteria: List[str] = Field(default_factory=list, description="Criteria for successful implementation")
    reasoning: str = Field(default="", description="Why this improvement is suggested")
    
    status: SuggestionStatus = Field(default=SuggestionStatus.PENDING)
    created_at: datetime = Field(default_factory=datetime.utcnow)
    
    # Implementation details (filled after worker completes)
    files_changed: List[str] = Field(default_factory=list)
    implementation_notes: str = Field(default="")
    iterations: int = Field(default=0, description="Number of worker-judge iterations")

    class Config:
        use_enum_values = True


class VerdictStatus(str, Enum):
    """Judge's verdict on implementation."""
    PASS = "pass"           # Implementation meets criteria
    FAIL = "fail"           # Implementation needs changes
    NEEDS_REVIEW = "needs_review"  # Unclear, needs human review


class Verdict(BaseModel):
    """Judge's assessment of a suggestion implementation."""
    suggestion_id: str
    status: VerdictStatus
    score: float = Field(default=0.0, ge=0.0, le=1.0, description="Quality score 0-1")
    feedback: str = Field(default="", description="Detailed feedback for the worker")
    criteria_met: List[str] = Field(default_factory=list, description="Which acceptance criteria passed")
    criteria_failed: List[str] = Field(default_factory=list, description="Which acceptance criteria failed")
    suggested_fixes: List[str] = Field(default_factory=list, description="Specific fixes to try")
    created_at: datetime = Field(default_factory=datetime.utcnow)

    class Config:
        use_enum_values = True


class RunStatus(str, Enum):
    """Status of an autonomous run."""
    PENDING = "pending"
    RUNNING = "running"
    PAUSED = "paused"       # User paused the run
    COMPLETED = "completed"
    FAILED = "failed"


class AutonomousRun(BaseModel):
    """A complete autonomous improvement run."""
    id: str = Field(default_factory=lambda: str(uuid.uuid4())[:8])
    target_repo: str = Field(..., description="Path to repository being improved")
    status: RunStatus = Field(default=RunStatus.PENDING)
    
    # Suggestions
    suggestions: List[Suggestion] = Field(default_factory=list)
    current_suggestion_index: int = Field(default=0)
    
    # Metrics
    total_suggestions: int = Field(default=0)
    accepted_count: int = Field(default=0)
    rejected_count: int = Field(default=0)
    completed_count: int = Field(default=0)
    failed_count: int = Field(default=0)
    
    # Timing
    started_at: Optional[datetime] = None
    completed_at: Optional[datetime] = None
    
    # Config snapshot
    model: str = Field(default="qwen2.5-coder:latest")
    max_iterations: int = Field(default=3)
    
    class Config:
        use_enum_values = True

    def get_current_suggestion(self) -> Optional[Suggestion]:
        """Get the current suggestion being processed."""
        if 0 <= self.current_suggestion_index < len(self.suggestions):
            return self.suggestions[self.current_suggestion_index]
        return None
    
    def advance(self) -> bool:
        """Move to next suggestion. Returns False if no more suggestions."""
        self.current_suggestion_index += 1
        return self.current_suggestion_index < len(self.suggestions)
